version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/Oghenesuvwe-dev/terraform-provider-digitalocean"

[[transformers]]
name = "gofmt"

[[transformers]]
name = "gofumpt"